version: '3.5'

services:
  base: &base
    build: .
    volumes:
      - .:/app

  tests:
    <<: *base
    command: py.test tests

  example:
    <<: *base
    command: python trip_sorter/example.py